# Generated by Django 4.2.1 on 2023-08-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='question_body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='question_pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question_title',
        ),
    ]
