# Generated by Django 4.2.1 on 2023-08-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_body_question_question_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_body',
            new_name='question_content',
        ),
    ]
