# Generated by Django 4.2.4 on 2023-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_rename_question_body_question_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
