# Generated by Django 4.2.1 on 2023-08-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_question_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_pub_date',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_title',
            new_name='title',
        ),
    ]
